### ISSUE TITLE
Manually Feature Testing - Augmentation Feature

### ISSUE THREAD

**Issue by Samyssmile** [Samyssmile/edux#120]
Conduct feature tests with various datasets to ensure the new augmentation feature functions optimally.

## Description
The recent integration of a new augmentation feature in our image processing pipeline needs to be thoroughly tested. This ticket is created to conduct feature tests using various datasets to evaluate the functionality and performance of the new feature.

## Tasks
- [ ] Select a diverse range of datasets for testing, including datasets of varying sizes.
- [ ] Apply the new augmentation feature to each dataset and observe the outcomes.
- [ ] Ensure that the feature's integration is seamless and that it performs as expected in different scenarios.
- [ ] Try different number of Threads
- [ ] Log any bugs or issues encountered during the testing in this ticket.

## Scope
Writing JUnit tests is not in the scope of this ticket.

## Datasets for testing
No matter what dataset you will use. If you dont have tons of datasets on your pc ;-). You can use our dataset generator tool.

- [GitHub FractalityLab v1.0](https://github.com/Samyssmile/fractalitylab)
Download the release jar and execute

Create 10000 Images fo each fractal class with 256 pixel size
`java -jar FractalityLab-1.0.jar 10000 256`
